int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
#import imp_libs += libhello%lib{hello}

# @@ Add pub_hdrs variable to break the complexity?
# @@ Combine the lib{foo} declaration:
#
#lib{foo}: {hxx ixx txx cxx}{** -config} hxx{config} \
#          $pub/{$($pub/pub_hdrs)} $imp_libs $int_libs

# Public headers.
#
pub = [dir_path] ../../include/libfoo/

include $pub

lib{foo}: $pub/{$($pub/pub_hdrs)}

# Private headers and sources as well as dependencies.
#
lib{foo}: {hxx ixx txx cxx}{** -config} hxx{config} $imp_libs $int_libs

hxx{config}: in{config}
{
  HELLO = "Hi"
}

# Build options.
#
out_inc = [dir_path] $out_root/include/
src_inc = [dir_path] $src_root/include/
out_src = [dir_path] $out_root/src/
src_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_src" "-I$src_src" \
                "-I$out_inc" "-I$src_inc"

obja{*}: cxx.poptions += -DLIBFOO_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBFOO_SHARED_BUILD

# Export options.
#
lib{foo}:
{
  cxx.export.poptions = "-I$out_inc" "-I$src_inc"
  cxx.export.libs = $int_libs
}

liba{foo}: cxx.export.poptions += -DLIBFOO_STATIC
libs{foo}: cxx.export.poptions += -DLIBFOO_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{foo}: bin.lib.version = @"-$version.project_id"
else
  lib{foo}: bin.lib.version = @"-$version.major.$version.minor"

# Don't install private headers.
#
{hxx ixx txx}{*}: install = false
