int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
#import imp_libs += libhello%lib{hello}

lib{foo}: {hxx ixx txx}{** -version} hxx{version} $imp_libs $int_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Export options.
#
out_inc = [dir_path] $out_root/include/
src_inc = [dir_path] $src_root/include/

lib{foo}:
{
  cxx.export.poptions = "-I$out_inc" "-I$src_inc"
  cxx.export.libs = $int_libs
}

# Install into the libfoo/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libfoo/
  install.subdirs = true
}
